// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	gql2 "airbnb-user-be/internal/app/currency/api/gql"
	repoimpl3 "airbnb-user-be/internal/app/currency/repo/repoimpl"
	usecaseimpl2 "airbnb-user-be/internal/app/currency/usecase/usecaseimpl"
	"airbnb-user-be/internal/app/locale/api/gql"
	repoimpl2 "airbnb-user-be/internal/app/locale/repo/repoimpl"
	"airbnb-user-be/internal/app/locale/usecase/usecaseimpl"
	"airbnb-user-be/internal/app/translation/repo/repoimpl"
	"airbnb-user-be/internal/pkg/env"
	"airbnb-user-be/internal/pkg/env/tool"
	"airbnb-user-be/internal/pkg/gorm"
	"airbnb-user-be/internal/pkg/http/server"
	"airbnb-user-be/internal/pkg/http/server/router"
	"github.com/google/wire"
)

import (
	_ "airbnb-user-be/docs"
)

// Injectors from wire.go:

func ProvideApp() (*App, error) {
	envConfig := env.ProvideDefaultEnvConf()
	config := env.ProvideEnv(envConfig)
	configConfig := tool.ExtractServerConfig(config)
	engine := router.ProvideRouter()
	options := server.Options{
		Config: configConfig,
		Router: engine,
	}
	serverServer := server.ProvideServer(options)
	config2 := tool.ExtractDBConfig(config)
	gormEngine := gorm.ProvideORM(config2)
	repoimplOptions := repoimpl.Options{
		Gorm: gormEngine,
	}
	repo := repoimpl.NewErrTranslationRepo(repoimplOptions)
	options2 := repoimpl2.Options{
		Gorm: gormEngine,
	}
	repoimplRepo := repoimpl2.NewLocaleRepo(options2)
	usecaseimplOptions := usecaseimpl.Options{
		LocaleRepo: repoimplRepo,
	}
	usecase := usecaseimpl.NewLocaleUsecase(usecaseimplOptions)
	gqlOptions := gql.Options{
		Locale: usecase,
	}
	handler := gql.ProvideLocaleHandler(gqlOptions)
	options3 := repoimpl3.Options{
		Gorm: gormEngine,
	}
	repo2 := repoimpl3.NewCurrencyRepo(options3)
	options4 := usecaseimpl2.Options{
		CurrencyRepo: repo2,
	}
	usecaseimplUsecase := usecaseimpl2.NewCurrencyUsecase(options4)
	options5 := gql2.Options{
		Currency: usecaseimplUsecase,
	}
	gqlHandler := gql2.ProvideCurrencyHandler(options5)
	appOptions := Options{
		HttpServer:         serverServer,
		Translation:        repo,
		LocaleGqlHandler:   handler,
		CurrencyGqlHandler: gqlHandler,
	}
	app := &App{
		Options: appOptions,
	}
	return app, nil
}

// wire.go:

var AppSet = wire.NewSet(wire.Struct(new(Options), "*"), wire.Struct(new(App), "*"))
