// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteLocale struct {
	Code string `json:"code"`
}

type Locale struct {
	Code     string  `json:"Code"`
	Name     string  `json:"Name"`
	Local    *string `json:"Local"`
	Location *string `json:"Location"`
	Lcid     int     `json:"LCID"`
	Iso639_2 *string `json:"ISO639_2"`
	Iso639_1 *string `json:"ISO639_1"`
}

type NewLocale struct {
	Code     string  `json:"Code"`
	Name     string  `json:"Name"`
	Local    *string `json:"Local"`
	Location *string `json:"Location"`
	Lcid     int     `json:"LCID"`
	Iso639_2 *string `json:"ISO639_2"`
	Iso639_1 *string `json:"ISO639_1"`
}
