// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Country struct {
	Iso       string  `json:"iso"`
	Iso3      *string `json:"iso_3"`
	Name      string  `json:"name"`
	NumCode   *int    `json:"numCode"`
	PhoneCode int     `json:"phoneCode"`
}

type Currency struct {
	Code   string `json:"code"`
	Symbol string `json:"symbol"`
	Name   string `json:"name"`
}

type DeleteLocale struct {
	Code string `json:"code"`
}

type Locale struct {
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Local     *string   `json:"local"`
	Location  *string   `json:"location"`
	Lcid      *int      `json:"lcid"`
	Iso639_2  *string   `json:"iso639_2"`
	Iso639_1  *string   `json:"iso639_1"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type NewLocale struct {
	Code     string  `json:"code"`
	Name     string  `json:"name"`
	Local    *string `json:"local"`
	Location *string `json:"location"`
	Lcid     *int    `json:"lcid"`
	Iso639_2 *string `json:"iso639_2"`
	Iso639_1 *string `json:"iso639_1"`
}

type Paging struct {
	Limit    *int `json:"limit"`
	Page     *int `json:"page"`
	PageSize *int `json:"pageSize"`
}
