// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Account struct {
	Provider     string    `json:"provider"`
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	ExpiredAt    time.Time `json:"expiredAt"`
	TokenType    string    `json:"tokenType"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type Countries struct {
	Data []*Country  `json:"data"`
	Meta *Pagination `json:"meta"`
}

type Country struct {
	Iso       string  `json:"iso"`
	Iso3      *string `json:"iso_3"`
	Name      string  `json:"name"`
	NumCode   *int    `json:"numCode"`
	PhoneCode int     `json:"phoneCode"`
}

type Currency struct {
	Code   string `json:"code"`
	Symbol string `json:"symbol"`
	Name   string `json:"name"`
}

type DeleteLocale struct {
	Code string `json:"code"`
}

type Locale struct {
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Local     *string   `json:"local"`
	Location  *string   `json:"location"`
	Lcid      *int      `json:"lcid"`
	Iso639_2  *string   `json:"iso639_2"`
	Iso639_1  *string   `json:"iso639_1"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type NewLocale struct {
	Code     string  `json:"code"`
	Name     string  `json:"name"`
	Local    *string `json:"local"`
	Location *string `json:"location"`
	Lcid     *int    `json:"lcid"`
	Iso639_2 *string `json:"iso639_2"`
	Iso639_1 *string `json:"iso639_1"`
}

type Pagination struct {
	Limit    *int `json:"limit"`
	Page     *int `json:"page"`
	PageSize *int `json:"pageSize"`
}

type User struct {
	FirstName      string              `json:"firstName"`
	FullName       string              `json:"fullName"`
	Email          *string             `json:"email"`
	CountryCode    *int                `json:"countryCode"`
	PhoneNumber    *string             `json:"phoneNumber"`
	Image          string              `json:"image"`
	Role           string              `json:"role"`
	DateOfBirth    time.Time           `json:"dateOfBirth"`
	CreatedAt      time.Time           `json:"createdAt"`
	UpdatedAt      time.Time           `json:"updatedAt"`
	VerifiedAt     *time.Time          `json:"verifiedAt"`
	DefaultSetting *UserDefaultSetting `json:"defaultSetting"`
	Accounts       []*Account          `json:"accounts"`
}

type UserDefaultSetting struct {
	Locale   string `json:"locale"`
	Currency string `json:"currency"`
}
