basePath: /auth
definitions:
  response.ContinueWithPhone:
    properties:
      isVerified:
        type: boolean
    type: object
host: localhost/api
info:
  contact:
    email: support@airbnb.co.id
    name: API Support
    url: https://airbnb.co.id/support
  description: Airbnb User Backend Service API
  termsOfService: https://airbnb.co.id
  title: Airbnb User Backend API
  version: "1.0"
paths:
  /sessions/facebook:
    get:
      responses: {}
      summary: Get session by using facebook oauth. User will be redirected to facebook
        sign in page to get credential and redirected back to service if user sign
        in correctly.
      tags:
      - auth
  /sessions/google:
    get:
      responses: {}
      summary: Get session by using google oauth. User will be redirected to google
        sign in page to get credential and redirected back to service if user sign
        in correctly.
      tags:
      - auth
  /sessions/phone/complete:
    post:
      responses: {}
      summary: Complete registration using phone number if not verified yet.
      tags:
      - auth
  /sessions/phone/generate:
    post:
      responses: {}
      summary: Make a session usign phone number if user already verified.
      tags:
      - auth
  /sessions/phone/initial:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.ContinueWithPhone'
      summary: Get session by using user phone number. An OTP code will be sent to
        user phone.
      tags:
      - auth
  /sessions/refresh:
    get:
      responses: {}
      summary: Rotate access and refresh tokens with a new one after access token
        expired.
      tags:
      - auth
  /sessions/signout:
    get:
      responses: {}
      summary: Delete user session by removing user access and refresh tokens.
      tags:
      - auth
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
