stage:
origins:
domain:
httpserver:
  host:
  port:
db:
  user:
  password:
  name:
  host:
  port:
  sslmode:
  timezone:
oauth:
  google:
    clientid:
    clientsecret:
    redirecturl:
    userinfoapi:
    scopes:
jwt:
  # from https://generate-secret.now.sh/32
  secret:
cache:
  auth:
    host:
    password:
    db: